### ISSUE TITLE
Add classic Gameboy color palette

### ISSUE THREAD

**Issue by R-Lovelett** [Kully/pixel-paint#11]
I saw your project and really enjoy how you created the accurate color palette for the NES to use. I would love to contribute by adding a toggle to switch to another palette - particularly the classic Gameboy with its 4-color green monochrome. Would that be alright?

**Comment by Kully** [comment]
@R-Lovelett Yes that would be amazing! Really happy that you are showing interest in the project.

For sure, I'm happy for you to set up a little toggle between NES and classic Gameboy.

Feel free to fork the project and create the PR. Also happy to look at your code along the journey if you want some 👀 on it.

**Comment by R-Lovelett** [comment]
Great! I appreciate the support! I'll most likely work on it more over the weekend, but I've been brainstorming and think it would be neat to have a toggle that would show/hide the appropriate color palettes while selected. I have a couple ideas on how this could potentially be accomplished, but I'll keep you posted in case I need a second set of eyes.

**Comment by Kully** [comment]
> 



> Great! I appreciate the support! I'll most likely work on it more over the weekend, but I've been brainstorming and think it would be neat to have a toggle that would show/hide the appropriate color palettes while selected. I have a couple ideas on how this could potentially be accomplished, but I'll keep you posted in case I need a second set of eyes.

Sounds great! Yeah, let me know what you are thinking. Would be happy to 👀 at it.

**Comment by R-Lovelett** [comment]
I spent some time yesterday night implementing the toggle I had mentioned to you before. I opted for radio buttons to switch out the color palettes depending on which one is considered "checked". If you'd like to take a look at the forked repository, I would be happy to show you what I've got so far.

**Comment by Kully** [comment]
> I spent some time yesterday night implementing the toggle I had mentioned to you before. I opted for radio buttons to switch out the color palettes depending on which one is considered "checked". If you'd like to take a look at the forked repository, I would be happy to show you what I've got so far.

Hey! Yes I'd love to see what you have so far. Let's see the forked repo! :)

**Comment by Kully** [comment]
@R-Lovelett  https://github.com/Kully/pixel-paint/pull/13
