### ISSUE TITLE
Swap between 2 colors on the fly

### ISSUE THREAD

**Issue by Kully** [Kully/pixel-paint#12]
Photoshop and other similar apps have a feature where you can save in memory 2 colors and swap between them with a click or a keyboard shortcut (eg. `X` in PhotoShop).

This would be a massive quality of life thing for the tool.

**Comment by aleksi100** [comment]
my fork have this feature now. It work by pressing c. What you think.

**Comment by Kully** [comment]
> What you think.

Wow! This is amazing! :) I love how easy it is to swap when making a piece, and I like how the active color at the top pops out.

If you make a PR to this repo, I'd be happy to look into getting it in the main project. :)
