### ISSUE TITLE
Cannot draw properly over Shortcuts area

### ISSUE THREAD

**Issue by pumpkinhasapatch** [Kully/pixel-paint#38]
My browser: Firefox 131.0.2

Having a problem where I am unable to draw over some of the pixels in the bottom-right corner of the canvas. This is where the keyboard shortcuts popup added in #28 appears when hovering over the "Shortcuts" button.

Dragging the mouse slowly over this area changes to the text select cursor and tries to highlight text from the Shortcuts popup (even if it's hidden), and moving quickly creates glitchy lines across the canvas.

Video: 
[Screencast from 2024-10-11 16-19-02.webm](https://github.com/user-attachments/assets/fb8e556a-fdf0-4397-97c9-4323a443d730)

**Comment by pumpkinhasapatch** [comment]
The issue also occurs on Chromium 129. How did this not get noticed before merging?

**Comment by Kully** [comment]
@pumpkinhasapatch Thank you so much for the catch.

Yes, I should have tested more thoroughly before merging.

It is now been hotfixed to `master` in [this commit](https://github.com/Kully/pixel-paint/commit/a9b52726598a0698621df9924e5db4b62e4e214f).

Thank you again.

**Comment by Kully** [comment]
Closing since addressed with https://github.com/Kully/pixel-paint/commit/a9b52726598a0698621df9924e5db4b62e4e214f
