### ISSUE TITLE
Line is drawn choppy on fast mouse movements

### ISSUE THREAD

**Issue by Kully** [Kully/pixel-paint#8]
## Issue
When you draw a line with your mouse very quickly across the screen, you get this choppy line. Would like the line to not have a bunch of gaps in it.

#### Idea for Solution
This will probably require some kind of interpolation as a user moves a mouse across the screen.

https://user-images.githubusercontent.com/10369095/156856405-011c9afe-7f77-485c-af14-27d9bc2c3b9a.mov

**Comment by HopefulFrog** [comment]
I dealt with this problem in a project of my own. What I did was get a Line object where the begin point is the mouse's location on the previous frame and the end point is the mouse's location on the current frame. Then I shortened the line to half the width of a pixel/square, still with the same begin point. Then, moving the shortened segment along the original line in increments equal to the shortened length, I filled in any pixels/squares that contained the end point of the segment during each increment.

**Comment by Kully** [comment]
> I'm working on a solution to this issue, but it is involving a complete rewriting of the way you handle the canvas. Instead of using individual divs, I'm using the javascript canvas element. This makes many things easier. It will soon be finished. You can take a look at my fork of the project to get an idea.

Amazing, so happy that you want to make a contribution to the project! 🎉

Yeah, the divs are definitely a little clunky. Honestly, the whole project was inspired by a blogpost where someone created a canvas-like structure made out of a grid of divs.

Excited to see what you come up with.

**Comment by Kully** [comment]
@gillo04 Any insights on your end? Juggling a few other projects so don't have the bandwidth to be in here that much. :)

**Comment by Kully** [comment]
Heads up, will probably start working on this soon. Lmk if you still want to contribute your branch.

**Comment by Viet281101** [comment]
Hey 👋
Me and @Raphaelmos are students at the Paris 8 University (French) and we'd love to be assigned to this task as part of our "free software development" course !
We are looking forward to contributing to this project and we are ready to start working on it.

**Comment by Kully** [comment]
Hi! Amazing, that would be great. :)

Im happy for you to open up a PR and get started on the feature.

Please feel free to ping me as well if you have any questions at all. 🙏

**Comment by Kully** [comment]
> We are looking forward to contributing to this project and we are ready to start working on it.

Out of curiosity, have you folks gotten a chance to start on this. No worries if you haven't :)

**Comment by Viet281101** [comment]
Hi @Kully , can you check my Pull Request?

**Comment by Kully** [comment]
Closing as resolved from #20
